### ISSUE TITLE
Features - RoadMap

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#240]
### Components

- Button
  - [x] SimpleButton #1 
  - [x] ToggleButton #1 
  - [x] ToggleGroup #1 
  - [x] MeasureButton #254 **v1.3.0**
  - [x] DigitzeButton #377 **v2.0.0**
  - [ ] ZoomInButton
  - [ ] ZoomOutButton
  - [ ] ZoomToExtentButton
  - [ ] GeoLocationButton
- CircleMenu
  - [x] CircleMenu #218 **v1.1.0**
- Field
  - [x] NominatimSearch #93 
  - [x] ScaleCombo #15 
  - [x] CoordinateReferenceSystemCombo #244 **v1.2.0**
  - [ ] HoverTemplateField --> https://ant.design/components/mention/
  - [ ] RemoteSelectField (AutoComplete with remote data source -> url as Prop …)
  - [ ] WFSSearchField (Maybe composoable with NominatimSearch)
- Grid 
  - [x] FeatureGrid #208 
    - [ ] Rename to AttributeGrid
  - [ ] RemoteGrid (Grid with remote data source -> url as Prop …)
- LayerTree
  - [x] LayerTree #30 
  - [x] LayerTreeNode --> should be moved to `LayerTree` folder (see CircleMenuItem) #30 
- Legend
  - [x] Legend #55 
- LayerPreview
  - [ ] LayerPreviewImage --> bismap
- LoadingMask
  - [ ] LoadingMask --> bismap
- Map
  - [x] FloatingMapLogo #15 
  - [x] MapComponent #195 
    - [ ] Drag & Drop Support
  - [ ] FeatureInfoPopup
- Panel
  - [x] Panel #30 
  - [x] Titlebar #30 
- Slider
  - [x] LayerTransparencySlider #68 
  - [x] WMS-T Slider #314 **v1.5.0**
  - [ ] MultipleLayerSlider (FadeIn/FadeOut)
- Toolbar
  - [x] Toolbar #10 
  - [x] HotizontalToolbar (via. Toolbar property) #10 
  - [x] VerticalToolbar (via. Toolbar property) #10 
- Userchip
  - [x] Userchip #4 
- LayerTree
  - [x] LayerTree #30
- Window
  - [x] Window #289  **v1.4.0**

### Container
- [ ] CoordinateTransformationPanel
- AddLayer-Components
  - [x] AddWMS-Components #267 **v1.4.0**
  - [ ] AddWFS-Components

### Utils

- [x] Csrf #2
- [x] AnimateUtil #377 
- [x] CapabilitiesUtil #267
- [ ] DigitizingUtil (WFS-T tools for drawing/digitizing tools)
- [x] FeatureUtil #30 
- [x] MapUtil #12 
- [x] ObjectUtil #9
- [x] ProjectionUtil #244
- [x] StringUtill #30 
- [x] UndoUtil #11
- [x] UrlUtil #42 
- [x] Logger #2

### HOCs

- [x] VisibleComponent #14 
- [x] MapProvider #195

**Comment by ahennr** [comment]
`ProjectionUtil` and `CoordinateReferenceSystemCombo` are introduced in https://github.com/terrestris/react-geo/pull/244

**Comment by urothstein** [comment]
- Slider Background-Maps (fadeIn / fadeOut between multiple layers)
- geolocation button
- drag & drop vector data support
- wfs search field? 
- layer filter field
- sld-components
- application-state serialize / deserialize / restore
- digitizing components and utils

**Comment by KaiVolland** [comment]
> - slider background-maps (fadeIn / fadeOut between multiple layers)
> - combo background-maps

The RemoteSelectField might be the component we want.
> - geolocation button
> - drag & drop vector data support
> - wfs search field? 
> - layer filter field
> - sld-components

Standalone Package Talk with @annarieger 
> - application-state serialize / deserialize / restore

This needs a state manager like redux. So its not sutiable for react-geo
- digitizing components and utils
> - rastercalculator

Standalone Package
> - attributecalculator

Standalone Package maybe joined with rastercalculator
> - coordinate-transformation-panel
> - feature/attribute-tables

Allready inlcuded. See FeatureGrid

**Comment by KaiVolland** [comment]
Moved to the wiki: https://github.com/terrestris/react-geo/wiki/Feature-List
